In [7]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
# Load data
file_name = "Titanic-Dataset.csv"
df = pd.read_csv(file_name)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [8]:
# Preprocessing
# Encoding categorical data
label_encoder = LabelEncoder()
df['Sex'] = label_encoder.fit_transform(df['Sex'])  # Convert 'Sex' to numerical
df["Embarked"].fillna(df['Embarked'].value_counts().idxmax(), inplace=True)
df["Age"].fillna(df["Age"].median(skipna=True), inplace=True)
print(df.isnull().sum())
# df['Embarked'].fillna('S', inplace=True)  # Fill missing 'Embarked' with 'S' for Southampton
#df['Embarked'] = label_encoder.fit_transform(df['Embarked'])  # Convert 'Embarked' to numerical
df = pd.get_dummies(df, columns=['Embarked','Pclass'])
# Convert True/False values to 0/1
df['Embarked_C'] = df['Embarked_C'].astype(int)
df['Embarked_Q'] = df['Embarked_Q'].astype(int)
df['Embarked_S'] = df['Embarked_S'].astype(int)
# Convert True/False values to 0/1 for Pclass
df['Pclass_1'] = df['Pclass_1'].astype(int)
df['Pclass_2'] = df['Pclass_2'].astype(int)
df['Pclass_3'] = df['Pclass_3'].astype(int)

df.drop(['Cabin','PassengerId', 'Name', 'Ticket','Fare'], axis=1, inplace=True)

# Handling missing values
# df['Age'].fillna(df['Age'].median(), inplace=True)  # Replace missing 'Age' with median value
df.head()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64


Survived  Sex   Age  SibSp  Parch  Embarked_C  Embarked_Q  Embarked_S  \
0         0    1  22.0      1      0           0           0           1   
1         1    0  38.0      1      0           1           0           0   
2         1    0  26.0      0      0           0           0           1   
3         1    0  35.0      1      0           0           0           1   
4         0    1  35.0      0      0           0           0           1   

   Pclass_1  Pclass_2  Pclass_3  
0         0         0         1  
1         1         0         0  
2         0         0         1  
3         1         0         0  
4         0         0         1

In [9]:
x = df[["Sex","Age","SibSp","Parch","Embarked_C","Embarked_Q","Embarked_S","Pclass_1","Pclass_2","Pclass_3"]]
y = df[["Survived"]]
X_train, X_test, Y_train, Y_test = train_test_split(x, y, random_state=0)
# Fit (train) the Support Vector Machine classifier
poly_svm_clf = SVC(kernel="poly")
poly_svm_model = poly_svm_clf.fit(X_train, Y_train)
poly_svm_prediction = poly_svm_clf.predict(X_test)
    
print("Accuracy {0:.2f}%".format(100*accuracy_score(poly_svm_prediction, Y_test)))

print(confusion_matrix(poly_svm_prediction, Y_test))

Accuracy 65.02%
[[139  78]
 [  0   6]]


d:\Miniconda3\envs\myenv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [10]:
# Fit (train) the Support Vector Machine classifier
linear_svm_clf = SVC(kernel = "linear")
linear_svm_model = linear_svm_clf.fit(X_train, Y_train)
linear_svm_prediction = linear_svm_clf.predict(X_test)

print("Accuracy {0:.2f}%".format(100*accuracy_score(linear_svm_prediction, Y_test)))

print(confusion_matrix(linear_svm_prediction, Y_test))

Accuracy 78.03%
[[115  25]
 [ 24  59]]


d:\Miniconda3\envs\myenv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
# Fit (train) the Support Vector Machine classifier
rbf_svm_clf = SVC(kernel = "rbf")
rbf_svm_model = rbf_svm_clf.fit(X_train, Y_train)
rbf_svm_prediction = rbf_svm_clf.predict(X_test)

print("Accuracy {0:.2f}%".format(100*accuracy_score(rbf_svm_prediction, Y_test)))

print(confusion_matrix(rbf_svm_prediction, Y_test))

Accuracy 65.47%
[[137  75]
 [  2   9]]


d:\Miniconda3\envs\myenv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [12]:
# Fit (train) the Support Vector Machine classifier
sigmoid_svm_clf = SVC(kernel = "sigmoid")
sigmoid_svm_model = sigmoid_svm_clf.fit(X_train, Y_train)
sigmoid_svm_prediction = sigmoid_svm_clf.predict(X_test)

print("Accuracy {0:.2f}%".format(100*accuracy_score(sigmoid_svm_prediction, Y_test)))

print(confusion_matrix(sigmoid_svm_prediction, Y_test))

Accuracy 60.54%
[[101  50]
 [ 38  34]]


d:\Miniconda3\envs\myenv\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
